version: "3.8"

services:
  siv-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SIV_SQL_Server
    user: "0"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
    volumes:
      - siv_db_data:/var/opt/mssql/data

  siv-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: SIV_API
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=siv-db,1433;Database=SIV_DB;User Id=sa;Password=${MSSQL_PASSWORD};TrustServerCertificate=True;
    depends_on:
      - siv-db

volumes:
  siv_db_data:
