// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIV.Infrastructure.Persistence;

#nullable disable

namespace SIV.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260616201204_AgregarNuevasEntidades")]
    partial class AgregarNuevasEntidades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIV.Domain.Entities.Aerolinea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Aerolineas");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Aeropuerto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Aeropuertos");
                });

            modelBuilder.Entity("SIV.Domain.Entities.HistorialCambioOperativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DetalleCambio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCambio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioResponsable")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VueloId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VueloId");

                    b.ToTable("HistorialCambiosOperativos");
                });

            modelBuilder.Entity("SIV.Domain.Entities.HistorialEstado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioResponsable")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VueloId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VueloId");

                    b.ToTable("HistorialEstados");
                });

            modelBuilder.Entity("SIV.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("LogAuditorias");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaHoraGenearicion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueLeida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioDestinatarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VueloRelacionadoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Seguimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VueloId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VueloId");

                    b.ToTable("Seguimientos");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PassWordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Vuelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Aerolinea")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Destino")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstadoActual")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("HorarioEstimadoLlegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HorarioEstimadoSalida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HorarioPlanificadoLlegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HorarioPlanificadoSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoUltimoCambio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroVuelo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("Origen")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Puerta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Aerolinea");

                    b.HasIndex("Destino");

                    b.HasIndex("Origen");

                    b.ToTable("Vuelos");
                });

            modelBuilder.Entity("SIV.Domain.Entities.HistorialCambioOperativo", b =>
                {
                    b.HasOne("SIV.Domain.Entities.Vuelo", null)
                        .WithMany("HistorialCambio")
                        .HasForeignKey("VueloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIV.Domain.Entities.HistorialEstado", b =>
                {
                    b.HasOne("SIV.Domain.Entities.Vuelo", null)
                        .WithMany("HistorialEstados")
                        .HasForeignKey("VueloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIV.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("SIV.Domain.Entities.Usuario", null)
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Seguimiento", b =>
                {
                    b.HasOne("SIV.Domain.Entities.Usuario", null)
                        .WithMany("Seguimientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIV.Domain.Entities.Vuelo", "Vuelo")
                        .WithMany()
                        .HasForeignKey("VueloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Vuelo", b =>
                {
                    b.HasOne("SIV.Domain.Entities.Aerolinea", "AerolineaRef")
                        .WithMany()
                        .HasForeignKey("Aerolinea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIV.Domain.Entities.Aeropuerto", "DestinoRef")
                        .WithMany()
                        .HasForeignKey("Destino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIV.Domain.Entities.Aeropuerto", "OrigenRef")
                        .WithMany()
                        .HasForeignKey("Origen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AerolineaRef");

                    b.Navigation("DestinoRef");

                    b.Navigation("OrigenRef");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Notificaciones");

                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Vuelo", b =>
                {
                    b.Navigation("HistorialCambio");

                    b.Navigation("HistorialEstados");
                });
#pragma warning restore 612, 618
        }
    }
}
