// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIV.Infrastructure.Persistence;

#nullable disable

namespace SIV.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260814145114_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIV.Domain.Entities.Catalogo.Aerolinea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Aerolineas");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Catalogo.Aeropuerto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Aeropuertos");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Sistema.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("LogAuditorias");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Sistema.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaHoraGenearicion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FueLeida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UsuarioDestinatarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VueloRelacionadoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Usuarios.Seguimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VueloId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VueloId");

                    b.ToTable("Seguimientos");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("IntentosFallidosLogin")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PassWordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Vuelos.HistorialCambioOperativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DetalleCambio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoCambio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioResponsable")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VueloId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VueloId");

                    b.ToTable("HistorialCambiosOperativos");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Vuelos.HistorialEstado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EstadoAnterior")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioResponsable")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VueloId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VueloId");

                    b.ToTable("HistorialEstados");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Vuelos.Vuelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Aerolinea")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Destino")
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoActual")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("HorarioEstimadoLlegada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HorarioEstimadoSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HorarioPlanificadoLlegada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HorarioPlanificadoSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoUltimoCambio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroVuelo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("Origen")
                        .HasColumnType("uuid");

                    b.Property<string>("Puerta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Aerolinea");

                    b.HasIndex("Destino");

                    b.HasIndex("Origen");

                    b.ToTable("Vuelos");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Sistema.Notificacion", b =>
                {
                    b.HasOne("SIV.Domain.Entities.Usuarios.Usuario", null)
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Usuarios.Seguimiento", b =>
                {
                    b.HasOne("SIV.Domain.Entities.Usuarios.Usuario", null)
                        .WithMany("Seguimientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIV.Domain.Entities.Vuelos.Vuelo", "Vuelo")
                        .WithMany()
                        .HasForeignKey("VueloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.OwnsMany("SIV.Domain.Entities.Usuarios.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<bool>("Codificado")
                                .HasColumnType("boolean");

                            b1.Property<string>("CreadoPorIp")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<DateTime>("FechaCreacion")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("FechaExpiracion")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("UsuarioId");

                            b1.ToTable("RefreshTokens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Vuelos.HistorialCambioOperativo", b =>
                {
                    b.HasOne("SIV.Domain.Entities.Vuelos.Vuelo", null)
                        .WithMany("HistorialCambio")
                        .HasForeignKey("VueloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIV.Domain.Entities.Vuelos.HistorialEstado", b =>
                {
                    b.HasOne("SIV.Domain.Entities.Vuelos.Vuelo", null)
                        .WithMany("HistorialEstados")
                        .HasForeignKey("VueloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIV.Domain.Entities.Vuelos.Vuelo", b =>
                {
                    b.HasOne("SIV.Domain.Entities.Catalogo.Aerolinea", "AerolineaRef")
                        .WithMany()
                        .HasForeignKey("Aerolinea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIV.Domain.Entities.Catalogo.Aeropuerto", "DestinoRef")
                        .WithMany()
                        .HasForeignKey("Destino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIV.Domain.Entities.Catalogo.Aeropuerto", "OrigenRef")
                        .WithMany()
                        .HasForeignKey("Origen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AerolineaRef");

                    b.Navigation("DestinoRef");

                    b.Navigation("OrigenRef");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.Navigation("Notificaciones");

                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("SIV.Domain.Entities.Vuelos.Vuelo", b =>
                {
                    b.Navigation("HistorialCambio");

                    b.Navigation("HistorialEstados");
                });
#pragma warning restore 612, 618
        }
    }
}
